# Generated by Django 2.0.4 on 2018-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burshlang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametr', models.FloatField()),
                ('coef', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stoyak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametr', models.FloatField()),
                ('coef', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vedtruba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametr', models.FloatField()),
                ('coef', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vertlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametr', models.FloatField()),
                ('coef', models.FloatField()),
            ],
        ),
    ]
