# Generated by Django 2.0.4 on 2018-04-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_nasos'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasos',
            name='coef',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
