# Generated by Django 2.0.4 on 2018-04-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_turbobur'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbobur',
            name='pgr',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
