# Generated by Django 2.0.4 on 2018-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_turbobur_pgr'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasos',
            name='qd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
